(() => {
const DATA_URL = '/data/bases-index.json';
const LEGACY_DATA_URL = '/data/bases.json';
const HERO_IMAGE_FALLBACK_URL = '/images/bases/placeholder.png';
const WIN_EPSILON = 0.05;
const MAX_SCORE = 10;

const LABELS = {
  type: {
    fortified_structure: 'Fortified Structure', isolated_landmass: 'Isolated Landmass', elevated_stronghold: 'Elevated Stronghold', subterranean: 'Subterranean', institutional_compound: 'Institutional Compound', industrial_site: 'Industrial Site', remote_settlement: 'Remote Settlement', transit_hub: 'Transit Hub', landmark_structure: 'Landmark Structure'
  },
  region: {
    uk_ireland: 'UK & Ireland', western_europe: 'Western Europe', eastern_europe: 'Eastern & Northern Europe', north_america: 'North America', south_america: 'South America', africa: 'Africa', middle_east: 'Middle East', south_asia: 'South Asia', east_asia: 'East Asia', southeast_asia: 'Southeast Asia', oceania: 'Oceania', polar_extreme: 'Polar & Extreme'
  }
};

const SCORE_ROWS = [
  { key: 'overall', label: 'Overall', source: 'overall', higherIsBetter: true, description: 'Composite survival score.' },
  { key: 'defensibility', label: 'Defensibility', source: 'category', higherIsBetter: true, description: 'Defensive strength and controlled access.' },
  { key: 'sustainability', label: 'Sustainability', source: 'category', higherIsBetter: true, description: 'Long-term food, water, energy and continuity.' },
  { key: 'isolation', label: 'Isolation', source: 'category', higherIsBetter: true, description: 'Separation from dense threat pressure.' },
  { key: 'exposure', label: 'Exposure Control', source: 'comparison', higherIsBetter: true, description: 'Higher score means lower practical exposure.' },
  { key: 'maintenanceBurden', label: 'Maintenance Resilience', source: 'comparison', higherIsBetter: true, description: 'Higher score means easier upkeep and lower burden.' },
  { key: 'populationCapacity', label: 'Population Capacity', source: 'comparison', higherIsBetter: true, description: 'Ability to support a larger group.' },
  { key: 'resourceSecurity', label: 'Resource Security', source: 'comparison', higherIsBetter: true, description: 'Reliability of useful local resources.' }
];
const ATTRIBUTE_ROWS = SCORE_ROWS.filter((row) => row.key !== 'overall');
const VERDICTS = [
  { key: 'earlySurvivalWinner', title: 'Best early survival', keys: ['defensibility', 'isolation', 'exposure'], reason: (winner) => `${winner.name} has the stronger first-phase blend of defensibility, isolation, and exposure control.` },
  { key: 'longTermWinner', title: 'Best long-term', keys: ['sustainability', 'resourceSecurity', 'populationCapacity'], reason: (winner) => `${winner.name} is better positioned after the first wave because sustainability, resources, and capacity carry the result.` },
  { key: 'lowMaintenanceWinner', title: 'Lowest maintenance', keys: ['maintenanceBurden'], reason: (winner) => `${winner.name} has the easier upkeep profile according to the maintenance resilience score.` }
];

const elements = {
  status: document.getElementById('compare-status'), page: document.getElementById('compare-page'), setup: document.getElementById('compare-setup'), notFound: document.getElementById('compare-not-found'), notFoundMessage: document.getElementById('compare-not-found-message'), title: document.getElementById('comparison-title'), heroA: document.getElementById('hero-base-a'), heroB: document.getElementById('hero-base-b'), scoreBaseA: document.getElementById('score-base-a'), scoreBaseB: document.getElementById('score-base-b'), overallSummary: document.getElementById('overall-winner-summary'), scoreBody: document.getElementById('score-comparison-body'), findings: document.getElementById('key-findings'), strengths: document.getElementById('strength-tradeoffs'), verdicts: document.getElementById('verdict-list'), compareCurrentPrimary: document.getElementById('compare-current-primary'), compareCurrentSecondary: document.getElementById('compare-current-secondary'), compareCurrentButton: document.getElementById('compare-current-button'), setupPrimary: document.getElementById('compare-setup-primary'), setupSecondary: document.getElementById('compare-setup-secondary'), setupButton: document.getElementById('compare-setup-button')
};
const slugHelper = window.baseSlugHelper;

function toTitleCaseSlug(value) { return String(value || '').split('_').map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(' '); }
function labelFor(kind, value) { return LABELS[kind][value] ?? toTitleCaseSlug(value); }
function isValidScoreValue(value) { return Number.isFinite(value); }
function formatScore(value) { return isValidScoreValue(value) ? value.toFixed(1) : '—'; }
function displayedTie(value) { return !isValidScoreValue(value) || Math.abs(value) < WIN_EPSILON; }
function formatDifference(value) { return !isValidScoreValue(value) || Math.abs(value) < WIN_EPSILON ? 'Even' : `+${Math.abs(value).toFixed(1)}`; }
function scoreToneClass(value) { if (!isValidScoreValue(value)) return ''; if (value >= 8) return 'score-high'; if (value >= 5) return 'score-medium'; return 'score-low'; }
function scoreLabel(value) { if (!isValidScoreValue(value)) return 'Unrated'; if (value >= 8.5) return 'Exceptional'; if (value >= 7) return 'Excellent'; if (value >= 5.5) return 'Good'; return 'Balanced'; }
function preferredSlugFor(baseOrSlug) { return slugHelper?.getPreferredSlug ? slugHelper.getPreferredSlug(baseOrSlug) : (typeof baseOrSlug === 'string' ? baseOrSlug : baseOrSlug?.slug || ''); }
function compareUrl(slugA, slugB) { return slugHelper?.getCompareUrl ? slugHelper.getCompareUrl(slugA, slugB) : `/base/${encodeURIComponent(slugA)}/vs/${encodeURIComponent(slugB)}`; }
function isCleanCompareRoute() { return slugHelper?.isCompareRoute ? slugHelper.isCompareRoute(window.location) : /^\/base\/[^/]+\/vs\/[^/]+\/?$/i.test(window.location.pathname); }
function baseUrl(base) { return slugHelper?.getBaseUrl ? slugHelper.getBaseUrl(base) : `/${encodeURIComponent(preferredSlugFor(base))}`; }
function getScore(base, rowOrKey) { const row = typeof rowOrKey === 'string' ? SCORE_ROWS.find((item) => item.key === rowOrKey) : rowOrKey; if (!row) return null; if (row.source === 'overall') return isValidScoreValue(base?.scores?.overall) ? base.scores.overall : null; if (row.source === 'category') return isValidScoreValue(base?.scores?.categories?.[row.key]) ? base.scores.categories[row.key] : null; return isValidScoreValue(base?.comparisonScores?.[row.key]?.score) ? base.comparisonScores[row.key].score : null; }
function normalizedDiff(baseA, baseB, row) { const scoreA = getScore(baseA, row); const scoreB = getScore(baseB, row); if (!isValidScoreValue(scoreA) || !isValidScoreValue(scoreB)) return null; return row.higherIsBetter ? scoreA - scoreB : scoreB - scoreA; }
function winnerFromDiff(diff) { if (!isValidScoreValue(diff) || Math.abs(diff) < WIN_EPSILON) return 'tie'; return diff > 0 ? 'baseA' : 'baseB'; }
function baseForWinner(result, winner) { return winner === 'baseA' ? result.baseA : winner === 'baseB' ? result.baseB : null; }
function shortName(base) { return String(base?.name || '').replace(/\s+(Island|Complex|Castle|Base|Plateau)$/i, '') || 'Base'; }
function compareRows(baseA, baseB, rows) { const total = rows.reduce((sum, row) => sum + (normalizedDiff(baseA, baseB, row) || 0), 0); return winnerFromDiff(total); }
function rowResult(baseA, baseB, row) { const baseAValue = getScore(baseA, row); const baseBValue = getScore(baseB, row); const rawDifference = isValidScoreValue(baseAValue) && isValidScoreValue(baseBValue) ? baseAValue - baseBValue : null; const decisiveDifference = normalizedDiff(baseA, baseB, row); return { ...row, baseAValue, baseBValue, rawDifference, decisiveDifference, absoluteDifference: isValidScoreValue(rawDifference) ? Math.abs(rawDifference) : null, winner: winnerFromDiff(decisiveDifference) }; }
function buildBaseComparison(baseA, baseB) {
  const metrics = SCORE_ROWS.map((row) => rowResult(baseA, baseB, row)).filter((metric) => isValidScoreValue(metric.baseAValue) || isValidScoreValue(metric.baseBValue));
  const attributes = metrics.filter((metric) => metric.key !== 'overall');
  const overallMetric = metrics.find((metric) => metric.key === 'overall');
  const byLargest = (items) => items.slice().sort((a, b) => (b.absoluteDifference || 0) - (a.absoluteDifference || 0));
  const largestBaseAAdvantage = byLargest(attributes.filter((metric) => metric.winner === 'baseA'))[0];
  const largestBaseBAdvantage = byLargest(attributes.filter((metric) => metric.winner === 'baseB'))[0];
  const closestMetric = attributes.slice().sort((a, b) => (a.absoluteDifference || 0) - (b.absoluteDifference || 0))[0];
  return {
    baseA, baseB, metrics, attributes, overallWinner: overallMetric?.winner || 'tie', overallMargin: overallMetric?.absoluteDifference || 0,
    baseAWins: attributes.filter((metric) => metric.winner === 'baseA').length,
    baseBWins: attributes.filter((metric) => metric.winner === 'baseB').length,
    ties: attributes.filter((metric) => metric.winner === 'tie').length,
    largestBaseAAdvantage, largestBaseBAdvantage, closestMetric,
    biggestDecidingFactor: byLargest(attributes.filter((metric) => metric.winner !== 'tie'))[0],
    earlySurvivalWinner: compareRows(baseA, baseB, SCORE_ROWS.filter((row) => ['defensibility', 'isolation', 'exposure'].includes(row.key))),
    longTermWinner: compareRows(baseA, baseB, SCORE_ROWS.filter((row) => ['sustainability', 'resourceSecurity', 'populationCapacity'].includes(row.key))),
    lowMaintenanceWinner: compareRows(baseA, baseB, SCORE_ROWS.filter((row) => row.key === 'maintenanceBurden'))
  };
}
function marginLabel(metric, result) { if (!isValidScoreValue(metric.decisiveDifference) || metric.winner === 'tie') return 'Even'; const base = baseForWinner(result, metric.winner); return `${formatDifference(metric.decisiveDifference)} ${shortName(base)}`; }
function explanationFor(result) { if (result.overallWinner === 'tie') return 'The bases are level on displayed overall score, so the category profile determines which mission each location suits best.'; const winner = baseForWinner(result, result.overallWinner); const loser = result.overallWinner === 'baseA' ? result.baseB : result.baseA; const primary = result.overallWinner === 'baseA' ? result.largestBaseAAdvantage : result.largestBaseBAdvantage; const loserEdge = result.overallWinner === 'baseA' ? result.largestBaseBAdvantage : result.largestBaseAAdvantage; return `${winner.name} leads through ${primary ? `a ${formatDifference(primary.decisiveDifference)} edge in ${primary.label}` : 'the overall scoring profile'}${loserEdge ? `, while ${loser.name} performs better in ${loserEdge.label}` : `, while ${loser.name} has no decisive category edge`}.`; }
function imageFor(base) { const slug = preferredSlugFor(base); return base.image || `/images/bases/${slug}.png`; }

function renderHeroCard(container, base, side, result) {
  const overall = getScore(base, 'overall'); const isWinner = result.overallWinner === side; const slug = preferredSlugFor(base);
  container.className = `versus-base-card${isWinner ? ' versus-base-card-winner' : ''}`; container.innerHTML = '';
  container.innerHTML = `<a class="versus-image-link" href="${baseUrl(base)}"><img class="versus-base-image" src="${imageFor(base)}" alt="${base.name} base image" loading="eager" decoding="async"></a><div class="versus-base-content"><div class="versus-card-top"><span class="badge ${isWinner ? 'badge-tier' : 'badge-trait'}">${isWinner ? 'Overall leader' : scoreLabel(overall)}</span><span class="versus-rank-marker" aria-hidden="true">${side === 'baseA' ? 'A' : 'B'}</span></div><p class="versus-score-label">Overall score</p><p class="detail-overall-score versus-overall-score ${scoreToneClass(overall)}">${isValidScoreValue(overall) ? `${formatScore(overall)}<span>/10</span>` : 'Score unavailable'}</p><h2><a href="${baseUrl(base)}">${base.name}</a></h2><p class="base-meta">${labelFor('type', base.type)} • ${labelFor('region', base.region)}</p><div class="badge-row"><span class="badge badge-trait">${labelFor('type', base.type)}</span><span class="badge badge-trait">${labelFor('region', base.region)}</span></div></div>`;
  container.querySelector('img').addEventListener('error', (event) => { event.currentTarget.src = HERO_IMAGE_FALLBACK_URL; }, { once: true });
}
function renderOverallSummary(result) { const winner = baseForWinner(result, result.overallWinner); elements.overallSummary.className = `overall-winner-summary ${winner ? 'has-winner' : 'is-tie'}`; elements.overallSummary.innerHTML = `<div class="summary-icon" aria-hidden="true">${winner ? '🏆' : '◆'}</div><div><p class="eyebrow">${winner ? 'Overall winner' : 'Overall result'}</p><h2>${winner ? winner.name : 'Too close to call'}</h2><p class="base-meta">${winner ? `Leads by ${formatDifference(result.overallMargin)} overall points` : 'The bases are level on overall score'}</p></div><div class="summary-copy"><p>${explanationFor(result)}</p><a href="#strengths-verdict">See key deciding factors →</a></div>`; }
function renderScoreRows(result) { elements.scoreBody.innerHTML = ''; elements.scoreBaseA.textContent = result.baseA.name; elements.scoreBaseB.textContent = result.baseB.name; result.metrics.forEach((metric) => { const aWin = metric.winner === 'baseA'; const bWin = metric.winner === 'baseB'; const item = document.createElement('article'); item.className = `score-comparison-row${metric.key === 'overall' ? ' is-overall' : ''}`; const aWidth = Math.max(0, Math.min(100, ((metric.baseAValue || 0) / MAX_SCORE) * 100)); const bWidth = Math.max(0, Math.min(100, ((metric.baseBValue || 0) / MAX_SCORE) * 100)); item.innerHTML = `<div class="score-metric"><strong>${metric.label}</strong><small>${metric.description || ''}</small></div><div class="score-bar-cell"><span class="score-num ${aWin ? 'score-cell-winner' : ''}">${formatScore(metric.baseAValue)}</span><div class="score-track" role="img" aria-label="${result.baseA.name} ${metric.label}: ${formatScore(metric.baseAValue)} out of 10, ${aWin ? 'leads' : bWin ? 'trails' : 'ties'}"><span class="score-fill score-fill-a" style="width:${aWidth}%"></span></div></div><div class="score-margin ${metric.winner === 'tie' ? 'score-difference-even' : 'score-difference-cell'}">${marginLabel(metric, result)}</div><div class="score-bar-cell score-bar-cell-b"><div class="score-track" role="img" aria-label="${result.baseB.name} ${metric.label}: ${formatScore(metric.baseBValue)} out of 10, ${bWin ? 'leads' : aWin ? 'trails' : 'ties'}"><span class="score-fill score-fill-b" style="width:${bWidth}%"></span></div><span class="score-num ${bWin ? 'score-cell-winner' : ''}">${formatScore(metric.baseBValue)}</span></div>`; elements.scoreBody.appendChild(item); }); }
function findingCard(label, title, body, meta) { return `<article class="insight-card"><p class="winner-card-label">${label}</p><h3>${title}</h3><p>${body}</p>${meta ? `<strong>${meta}</strong>` : ''}</article>`; }
function renderFindings(result) { const winner = baseForWinner(result, result.overallWinner); const winnerEdge = result.overallWinner === 'baseA' ? result.largestBaseAAdvantage : result.overallWinner === 'baseB' ? result.largestBaseBAdvantage : result.biggestDecidingFactor; const weakness = result.overallWinner === 'baseA' ? result.largestBaseBAdvantage : result.overallWinner === 'baseB' ? result.largestBaseAAdvantage : null; elements.findings.innerHTML = findingCard('Key advantage', winnerEdge?.label || 'No clear edge', winnerEdge ? `${baseForWinner(result, winnerEdge.winner).name} leads this metric by ${formatDifference(winnerEdge.decisiveDifference)}.` : 'No single metric separates the two bases.', winnerEdge ? `Gap ${formatDifference(winnerEdge.decisiveDifference)}` : '') + findingCard('Key weakness', weakness?.label || 'No clear weakness', weakness && winner ? `${winner.name} gives ground to ${baseForWinner(result, weakness.winner).name} in this category.` : `${winner ? winner.name : 'Neither base'} leads or ties across the relevant measured categories.`, weakness ? `Gap ${formatDifference(weakness.decisiveDifference)}` : '') + findingCard('Closest match', result.closestMetric?.label || 'No comparable metric', result.closestMetric ? `${result.closestMetric.winner === 'tie' ? 'The bases are even here.' : `Only ${formatDifference(result.closestMetric.decisiveDifference)} separates the two.`}` : 'No shared metric was available.', result.closestMetric ? marginLabel(result.closestMetric, result) : '') + findingCard('Score breakdown', `${result.baseAWins}-${result.baseBWins}-${result.ties}`, `${result.baseA.name}: ${result.baseAWins} wins. ${result.baseB.name}: ${result.baseBWins} wins. Ties: ${result.ties}.`, 'Non-overall metrics'); }
function renderStrengths(result) { elements.strengths.innerHTML = [ ['baseA', result.baseA], ['baseB', result.baseB] ].map(([side, base]) => { const wins = result.attributes.filter((m) => m.winner === side).sort((a,b)=>(b.absoluteDifference||0)-(a.absoluteDifference||0)).slice(0,3); const losses = result.attributes.filter((m) => m.winner !== side && m.winner !== 'tie').sort((a,b)=>(b.absoluteDifference||0)-(a.absoluteDifference||0)).slice(0,2); return `<article class="tradeoff-card"><h3>${base.name}</h3><p class="winner-card-label">Strengths</p><ul>${wins.length ? wins.map((m)=>`<li>Leads in ${m.label} by ${formatDifference(m.decisiveDifference)}.</li>`).join('') : '<li>No decisive scoring advantages.</li>'}</ul><p class="winner-card-label">Trade-offs</p><ul>${losses.length ? losses.map((m)=>`<li>Trails in ${m.label} by ${formatDifference(m.decisiveDifference)}.</li>`).join('') : '<li>No clear scoring liabilities.</li>'}</ul></article>`; }).join(''); }
function renderVerdicts(result) { const overall = baseForWinner(result, result.overallWinner); document.getElementById('verdict-heading').textContent = overall ? `${overall.name} is the stronger choice for long-term survival.` : 'This matchup is too close to call overall.'; elements.verdicts.innerHTML = VERDICTS.map((verdict) => { const side = result[verdict.key]; const winner = baseForWinner(result, side); return `<article class="verdict-card"><p class="winner-card-label">${verdict.title}</p><h3>${winner ? winner.name : 'Even'}</h3><p>${winner ? verdict.reason(winner) : 'The weighted score inputs are effectively even, so neither base has a deterministic edge here.'}</p></article>`; }).join('') + `<article class="verdict-card"><p class="winner-card-label">Biggest deciding factor</p><h3>${result.biggestDecidingFactor?.label || 'Even'}</h3><p>${result.biggestDecidingFactor ? `${baseForWinner(result, result.biggestDecidingFactor.winner).name} leads by ${formatDifference(result.biggestDecidingFactor.decisiveDifference)}.` : 'No decisive category margin is available.'}</p></article>`; }
function populateSelect(select, bases, options = {}) { select.innerHTML = ''; if (options.placeholder) select.append(new Option(options.placeholder, '')); bases.filter((base) => preferredSlugFor(base) !== options.excludeSlug).slice().sort((a, b) => a.name.localeCompare(b.name)).forEach((base) => select.append(new Option(base.name, preferredSlugFor(base)))); if (options.value) select.value = options.value; }
function updatePickerButton() { const invalid = !elements.compareCurrentPrimary.value || !elements.compareCurrentSecondary.value || elements.compareCurrentPrimary.value === elements.compareCurrentSecondary.value; elements.compareCurrentButton.disabled = invalid; }
function updateMetadata(baseA, baseB) { if (!window.seo) return; const title = `${baseA.name} vs ${baseB.name} | Zombie Bases`; const description = `Compare ${baseA.name} and ${baseB.name} across survival scores, category winners, biggest advantages, and deterministic verdicts.`; const canonicalPath = `/base/${preferredSlugFor(baseA)}/vs/${preferredSlugFor(baseB)}`; const canonicalUrl = `${window.seo.PRODUCTION_ORIGIN}${canonicalPath}`; window.seo.applyPageMetadata({ title, description, canonicalPath, canonicalParams: null }); window.seo.applySocialMetadata({ title, description, url: canonicalUrl, type: 'website', image: `${window.seo.PRODUCTION_ORIGIN}/images/bases/${encodeURIComponent(preferredSlugFor(baseA))}.png` }); }
function pushCleanCompareUrl(baseA, baseB) { const cleanPath = compareUrl(preferredSlugFor(baseA), preferredSlugFor(baseB)); if (cleanPath) window.history.pushState({}, '', cleanPath); }
function syncCleanCompareUrl(baseA, baseB) { const cleanPath = compareUrl(preferredSlugFor(baseA), preferredSlugFor(baseB)); if (cleanPath && !isCleanCompareRoute()) window.history.replaceState({}, '', cleanPath); }
function renderComparison(baseA, baseB, bases) { const result = buildBaseComparison(baseA, baseB); elements.title.textContent = `${baseA.name} vs ${baseB.name}`; renderHeroCard(elements.heroA, baseA, 'baseA', result); renderHeroCard(elements.heroB, baseB, 'baseB', result); renderOverallSummary(result); renderScoreRows(result); renderFindings(result); renderVerdicts(result); renderStrengths(result); const slugA = preferredSlugFor(baseA); const slugB = preferredSlugFor(baseB); populateSelect(elements.compareCurrentPrimary, bases, { value: slugA, excludeSlug: slugB }); populateSelect(elements.compareCurrentSecondary, bases, { value: slugB, excludeSlug: slugA }); elements.compareCurrentPrimary.onchange = () => { populateSelect(elements.compareCurrentSecondary, bases, { value: elements.compareCurrentSecondary.value, excludeSlug: elements.compareCurrentPrimary.value }); updatePickerButton(); }; elements.compareCurrentSecondary.onchange = () => { populateSelect(elements.compareCurrentPrimary, bases, { value: elements.compareCurrentPrimary.value, excludeSlug: elements.compareCurrentSecondary.value }); updatePickerButton(); }; elements.compareCurrentButton.onclick = () => { const nextSlugA = elements.compareCurrentPrimary.value; const nextSlugB = elements.compareCurrentSecondary.value; if (!nextSlugA || !nextSlugB || nextSlugA === nextSlugB) return; const nextBaseA = slugHelper?.resolveBaseBySlug?.(bases, nextSlugA) || bases.find((base) => preferredSlugFor(base) === nextSlugA); const nextBaseB = slugHelper?.resolveBaseBySlug?.(bases, nextSlugB) || bases.find((base) => preferredSlugFor(base) === nextSlugB); if (!nextBaseA || !nextBaseB) return showNotFound(`We couldn't find ${[!nextBaseA ? nextSlugA : null, !nextBaseB ? nextSlugB : null].filter(Boolean).join(' and ')} in the current base dataset.`); pushCleanCompareUrl(nextBaseA, nextBaseB); renderComparison(nextBaseA, nextBaseB, bases); window.scrollTo({ top: 0, behavior: 'smooth' }); }; updatePickerButton(); syncCleanCompareUrl(baseA, baseB); updateMetadata(baseA, baseB); elements.status.textContent = ''; elements.setup.hidden = true; elements.notFound.hidden = true; elements.page.hidden = false; }
function getRequestedSlugs() { const params = new URLSearchParams(window.location.search); const cleanCompareSlugs = slugHelper?.getCompareSlugsFromLocation?.(window.location); if (cleanCompareSlugs) return { slugA: cleanCompareSlugs.baseSlug, slugB: cleanCompareSlugs.compareSlug }; return { slugA: params.get('a') || params.get('base') || '', slugB: params.get('b') || params.get('against') || '' }; }
function showNotFound(message) { elements.status.textContent = ''; elements.page.hidden = true; elements.setup.hidden = true; elements.notFoundMessage.textContent = message; elements.notFound.hidden = false; }
function showSetup(bases, slugA = '', slugB = '') { populateSelect(elements.setupPrimary, bases, { placeholder: 'Select first base', value: slugA }); populateSelect(elements.setupSecondary, bases, { placeholder: 'Select second base', value: slugB, excludeSlug: slugA }); elements.setupPrimary.onchange = () => populateSelect(elements.setupSecondary, bases, { placeholder: 'Select second base', excludeSlug: elements.setupPrimary.value, value: elements.setupSecondary.value }); elements.setupButton.onclick = () => { const nextBaseA = slugHelper?.resolveBaseBySlug?.(bases, elements.setupPrimary.value) || bases.find((base) => preferredSlugFor(base) === elements.setupPrimary.value); const nextBaseB = slugHelper?.resolveBaseBySlug?.(bases, elements.setupSecondary.value) || bases.find((base) => preferredSlugFor(base) === elements.setupSecondary.value); if (nextBaseA && nextBaseB && nextBaseA !== nextBaseB) { pushCleanCompareUrl(nextBaseA, nextBaseB); renderComparison(nextBaseA, nextBaseB, bases); } }; elements.status.textContent = ''; elements.page.hidden = true; elements.notFound.hidden = true; elements.setup.hidden = false; }
async function loadBasesData() { let lastError = null; for (const url of [DATA_URL, LEGACY_DATA_URL]) { try { const response = await fetch(url); if (!response.ok) { lastError = new Error(`Failed to load base data from ${url} (${response.status})`); continue; } const payload = await response.json(); if (Array.isArray(payload)) return payload; if (Array.isArray(payload?.bases)) return payload.bases; lastError = new Error(`Unexpected base data shape from ${url}`); } catch (error) { lastError = error; } } throw lastError || new Error('Unable to load base data'); }
async function initComparison() { if ([elements.status, elements.page, elements.setup, elements.notFound, elements.notFoundMessage].some((element) => !element)) return; elements.status.textContent = 'Loading comparison...'; try { const bases = await loadBasesData(); const { slugA, slugB } = getRequestedSlugs(); const baseA = slugA ? slugHelper?.resolveBaseBySlug?.(bases, slugA) || bases.find((base) => preferredSlugFor(base) === slugA) : null; const baseB = slugB ? slugHelper?.resolveBaseBySlug?.(bases, slugB) || bases.find((base) => preferredSlugFor(base) === slugB) : null; if (slugA && slugB && preferredSlugFor(slugA) === preferredSlugFor(slugB)) return showNotFound('Choose two different bases to compare. This comparison URL uses the same base on both sides.'); if ((slugA && !baseA) || (slugB && !baseB)) return showNotFound(`We couldn't find ${[slugA && !baseA ? slugA : null, slugB && !baseB ? slugB : null].filter(Boolean).join(' and ')} in the current base dataset.`); if (!baseA || !baseB) return showSetup(bases, baseA ? preferredSlugFor(baseA) : slugA, baseB ? preferredSlugFor(baseB) : slugB); renderComparison(baseA, baseB, bases); } catch (error) { console.error(error); showNotFound('The comparison data could not be loaded. Please try again later.'); } }
window.zombieBasesComparison = { SCORE_ROWS, buildBaseComparison, formatScore, formatDifference };
initComparison();
})();
